# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScratchLayer', '0002_remove_users_email_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
