# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ScratchLayer', '0003_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_text', models.CharField(max_length=30)),
                ('email_text', models.CharField(max_length=100)),
                ('password_text', models.CharField(max_length=30)),
            ],
        ),
    ]
