# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScratchLayer', '0004_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email_text',
        ),
    ]
